// <auto-generated />
using manicureAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace manicureAPI.Migrations
{
    [DbContext(typeof(manicureAPIContext))]
    partial class manicureAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("manicureAPI.Models.Endereco", b =>
                {
                    b.Property<Guid>("EnderecoId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("Bairro")
                        .IsRequired();

                    b.Property<string>("CEP")
                        .IsRequired();

                    b.Property<string>("Cidade")
                        .IsRequired();

                    b.Property<DateTime?>("DataAlterou");

                    b.Property<DateTime>("DataCadastrou");

                    b.Property<string>("Logradouro")
                        .IsRequired();

                    b.Property<string>("Numero")
                        .IsRequired();

                    b.Property<int>("UF");

                    b.Property<Guid?>("UsuarioAlterou");

                    b.Property<Guid>("UsuarioCadastrou");

                    b.HasKey("EnderecoId");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("manicureAPI.Models.Usuario", b =>
                {
                    b.Property<Guid>("usuarioId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo");

                    b.Property<string>("CPF")
                        .IsRequired();

                    b.Property<DateTime?>("DataAlterou");

                    b.Property<DateTime>("DataCadastrou");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<Guid>("EnderecoId");

                    b.Property<string>("IdFirebase");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<double?>("Preco");

                    b.Property<string>("Skype");

                    b.Property<Guid?>("UsuarioAlterou");

                    b.Property<Guid>("UsuarioCadastrou");

                    b.Property<string>("Whatsapp");

                    b.Property<int>("tipoUsuario");

                    b.HasKey("usuarioId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("manicureAPI.Models.Usuario", b =>
                {
                    b.HasOne("manicureAPI.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
